import { Montserrat } from 'next/font/google'
import Head from 'next/head'


const montserrat = Montserrat({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className=''>
        Home
      </main>
    </>
  )
}
